#!/bin/bash
# run from system-build

mkdir ~/images >& /dev/null

echo system-build > ~/images/tags
git branch >> ~/images/tags
git describe >> ~/images/tags
echo >> ~/images/tags

echo buildroot >> ~/images/tags
cd ../buildroot
git branch >> ~/images/tags
git describe >> ~/images/tags
cd ../system-build
echo >> ~/images/tags

echo go >> ~/images/tags
cd ../go
git branch >> ~/images/tags
git describe >> ~/images/tags
cd ../system-build
echo >> ~/images/tags >> ~/images/tags

echo src/u-boot >> ~/images/tags
cd src/u-boot
git branch >> ~/images/tags
git describe >> ~/images/tags
cd ../..
echo >> ~/images/tags

echo src/linux >> ~/images/tags
cd src/linux
git branch >> ~/images/tags
git describe >> ~/images/tags
cd ../..
echo >> ~/images/tags

echo src/coreboot >> ~/images/tags
cd src/coreboot >> ~/images/tags
git branch >> ~/images/tags
git describe >> ~/images/tags
cd ../..
echo >> ~/images/tags

echo src/coreboot/3rdparty/arm-trusted-firmware >> ~/images/tags
cd src/coreboot/3rdparty/arm-trusted-firmware
git branch >> ~/images/tags
git describe >> ~/images/tags
cd ../../../..
echo >> ~/images/tags

echo src/coreboot/3rdparty/blobs >> ~/images/tags
cd src/coreboot/3rdparty/blobs
git branch >> ~/images/tags
git describe >> ~/images/tags
cd ../../../..
echo >> ~/images/tags

echo src/coreboot/3rdparty/chromeec >> ~/images/tags
cd src/coreboot/3rdparty/chromeec
git branch >> ~/images/tags
git describe >> ~/images/tags
cd ../../../..
echo >> ~/images/tags

echo src/coreboot/3rdparty/intel-blobs >> ~/images/tags
cd src/coreboot/3rdparty/intel-blobs
git branch >> ~/images/tags
git describe >> ~/images/tags
cd ../../../..
echo >> ~/images/tags

echo src/coreboot/3rdparty/libhwbase >> ~/images/tags
cd src/coreboot/3rdparty/libgfxinit
git branch >> ~/images/tags
git describe >> ~/images/tags
cd ../../../..
echo >> ~/images/tags

echo src/coreboot/3rdparty/libgfxinit >> ~/images/tags
cd src/coreboot/3rdparty/libgfxinit
git branch >> ~/images/tags
git describe >> ~/images/tags
cd ../../../..
echo >> ~/images/tags

echo src/coreboot/3rdparty/vboot >> ~/images/tags
cd src/coreboot/3rdparty/vboot
git branch >> ~/images/tags
git describe >> ~/images/tags
cd ../../../..
echo >> ~/images/tags

echo fe1 >> ~/images/tags
cd ../fe1
git branch >> ~/images/tags
git describe >> ~/images/tags
cd ../system-build
echo >> ~/images/tags

echo firmware-fe1a >> ~/images/tags
cd ../firmware-fe1a
git branch >> ~/images/tags
git describe >> ~/images/tags
cd ../system-build
echo >> ~/images/tags

