#!/bin/bash
# nightly build
#
# images will be in ~/nightly/master/images
# buildlogs in ~/nightly/master/buildlogs, includes 'git describe' for built with tags
#

source ~/.bashrc &> /dev/null
rm ~/gopath/src/github.com/platinasystems/go/main/goes-platina-mk1/goes-platina-mk1 &> /dev/null

mkdir ~/nightly >& /dev/null
mkdir ~/nightly/master >& /dev/null
mkdir ~/nightly/master/images >& /dev/null
mkdir ~/nightly/master/buildlogs >& /dev/null

regression_server=172.17.2.28
_now=$(date +"%F:%H:%M:%M")
_file="goes-platina-mk1-$_now"
_filei="goes-platina-mk1-installer-$_now"
_logfile="buildlog-goes-platina-mk1-$_now"

echo "fe1" > ~/logfile
cd ~/gopath/src/github.com/platinasystems/fe1
git checkout master
git fetch &>> ~/logfile
git pull &>> ~/logfile
git describe >> ~/logfile

echo >> ~/logfile
echo "firmware-fe1a" >> ~/logfile
cd ~/gopath/src/github.com/platinasystems/firmware-fe1a
git fetch &>> ~/logfile
git pull &>> ~/logfile
git describe >> ~/logfile

echo >> ~/logfile
echo "go" >> ~/logfile
cd ~/gopath/src/github.com/platinasystems/go
git checkout master
cd ~/gopath/src/github.com/platinasystems/go/main/goes-platina-mk1
git fetch &>> ~/logfile
git pull &>> ~/logfile
git describe >> ~/logfile

echo >> ~/logfile
echo "make" >> ~/logfile
#make fe1a.zip >> ~/logfile

# check if tags are the same
grep "v" ~/logfile | grep -v "vfio" | sum > ~/t2
grep "v" ~/lastfile | grep -v "vfio" | sum > ~/t3
file1=`sum ~/t2`
file2=`sum ~/t3`
if [ "$file1" = "$file2" ]
then
    echo "Files have the same content"
    exit
fi

make -B goes-platina-mk1 &>> ~/logfile
make -B goes-platina-mk1-installer

echo done >> ~/logfile
cp ~/logfile ~/lastfile
mv ~/gopath/src/github.com/platinasystems/go/main/goes-platina-mk1/goes-platina-mk1 ~/nightly/master/images/$_file
rm ~/nightly/master/images/goes-platina-mk1-latest
ln -s ~/nightly/master/images/$_file ~/nightly/master/images/goes-platina-mk1-latest

mv ~/gopath/src/github.com/platinasystems/go/main/goes-platina-mk1/goes-platina-mk1-installer ~/nightly/master/images/$_filei
rm ~/nightly/master/images/goes-platina-mk1-installer-latest
ln -s ~/nightly/master/images/$_filei ~/nightly/master/images/goes-platina-mk1-installer-latest
scp -p ~/nightly/master/images/goes-platina-mk1-installer-latest $regression_server:~/master

mv ~/logfile ~/nightly/master/buildlogs/$_logfile

