#!/bin/bash

source scripts/mk-bmc-env
source scripts/mk-bmc-ubo
source scripts/mk-bmc-ini

rm -rf ./tmp2
mkdir tmp2

cp platina-mk1-bmc-env.bin tmp2
cp platina-mk1-bmc-ubo.bin tmp2
cp initrd.img.xz tmp2/platina-mk1-bmc-ini.bin
cp platina-mk1-bmc.vmlinuz tmp2/platina-mk1-bmc-ker.bin
cp platina-mk1-bmc.dtb tmp2/platina-mk1-bmc-dtb.bin

cd tmp2
zip -r ../platina-mk1-bmc.zip .

cd ..
rm -rf ./tmp2

