#!/bin/bash

dd if=/dev/zero of=file2000 bs=8192 count=1

tr '\012' '\000' < scripts/mk1-bmc-envvars > platina-mk1-bmc-env

cat platina-mk1-bmc-env file2000 > platina-mk1-bmc-env.b

truncate -s 8188 platina-mk1-bmc-env.b

crc32 platina-mk1-bmc-env.b > crc.ascii

go run scripts/crc.go

cat crc platina-mk1-bmc-env.b > platina-mk1-bmc-env.bin

rm file2000 platina-mk1-bmc-env platina-mk1-bmc-env.b crc.ascii crc
