#!/bin/bash
# nightly kernel build
#
# kernel images will be in ~/nightly
# buildlogs in ~/nightly/buildlogs, includes 'git describe' for built with tags
#

usage () {
    echo "Usage: $0 <branch_name>"
    exit 1
}

if [ $# -lt 1 ]; then
    usage
fi

my_branch=$1

source ~/.bashrc &>/dev/null

mkdir -p ~/nightly/$my_branch/buildlogs &>/dev/null

regression_server=172.17.2.28
_now=$(date +"%F:%H:%M:%M")
_logfile="buildlog-mk1-linux-$my_branch-$_now"

rm ~/$_logfile &>/dev/null
echo $_now > ~/$_logfile
echo >> ~/$_logfile

for cpnt in system-build system-build/src/buildroot system-build/src/coreboot system-build/src/linux system-build/src/u-boot
do
  cd ~/gopath/src/github.com/platinasystems/$cpnt
  echo "Update $cpnt..." >> ~/$_logfile
  git checkout $my_branch >> ~/$_logfile 
  git pull >> ~/$_logfile
done

cd ~/gopath/src/github.com/platinasystems/system-build
my_build=`make help | grep linux-i`
ls $my_build >> ~/$_logfile
if [ $? -eq 0 ]
then
    echo "build exists, done." >> ~/$_logfile
    mv ~/$_logfile ~/nightly/$my_branch/buildlogs
    exit
fi

echo >> ~/$_logfile
echo "Build..." >> ~/$_logfile
rm -rf linux >> ~/$_logfile
make -B $my_build >> ~/$_logfile 

echo >> ~/$_logfile
echo Done >> ~/$_logfile

scp -p $my_build $regression_server:~/$my_branch
mkdir -p ~/nightly/$my_branch/images &>/dev/null
cp -p  $my_build ~/nightly/$my_branch/images
mv ~/$_logfile ~/nightly/$my_branch/buildlogs
